version: '3'

services:
  frontend:
    build:
      context: ./src 
    ports:
      - "3000:3000"         
    volumes:
      - ./src:/usr/src/app 
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000"       
    volumes:
      - ./backend:/usr/src/app  
    depends_on:
      - mongo  
      - redis  

  mongo:
    image: mongo
    ports:
      - "27017:27017"  

  redis:
    image: redis
    ports:
      - "6379:6379"   
